spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin123
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /**
  resource:
    static-location: classpath:/static/


logging:
  level:
    edu.hue.jk.mapper: debug

server:
  port: 8080
  servlet:
    context-path: /bookstore

bookstore:
  url-locations: productImg
  upload-locations: d:\bookstore\productImg
  url-path: /productImg/**/*